name: Publish to NuGet
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Build, pack & publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - Kpax.Abstraction
          - Kpax.Core
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200
          
      - name: Debug project name
        run: echo 'Source/{{ matrix.project }}/{{ matrix.project }}.csproj'

      # Publish
      - name: Publish {{ matrix.project }} on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Source/{{ matrix.project }}/{{ matrix.project }}.csproj
          
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true
